# Permalinks
permalink:        pretty

# Setup
title:            Lucas Tétreault
tagline:          'a tech blog'
description:      'Software architect and developer.'
url:              https://lucastetreault.ca
baseurl:          /blog

author:
  name:           'Lucas Tétreault'
  url:            https://twitter.com/ltetreault

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lucastetreault
