# Permalinks
permalink:        pretty

# Setup
title:            Lucas Tétreault
tagline:          'a tech blog'
description:      'A software developer with nearly a decade of experience. Passionate about quality and xp practices such as test driven development, pair programming and automated testing.'
url:              http://lucastetreault.ca
baseurl:          /blog

author:
  name:           'Lucas Tétreault'
  url:            https://twitter.com/ltetreault

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/lucastetreault
